services:
    frontend:
        image: nginx:stable-alpine
        ports:
            - "8090:80"
        environment:
            - VUE_APP_TITLE=OrangeJudge
            - BACKEND_LINK=http://host.docker.internal:8080
            - WORKER_PROCESSES=4
        volumes:
            - ../dist:/usr/share/nginx/html:rw
            - ../tools:/tools
        extra_hosts:
            - "host.docker.internal:host-gateway"
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost" ]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 20s
        entrypoint:
            - "/tools/entrypoint-test.sh"